name: publish

on:
  release:
    types:
      - published

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup
        uses: actions/setup-go@v2
        with:
          go-version: "1.19"
      - name: build
        run: |
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o duuh-linux-amd64
          CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build -o duuh-darwin-amd64
      - uses: softprops/action-gh-release@v1
        with:
          files: |
            duuh-linux-amd64
            duuh-darwin-amd64
